### ISSUE TITLE
Vehicle compiling loss functions which aren't properties

### ISSUE THREAD

**Issue by Tgl70** [vehicle-lang/vehicle#182]
Vehicle does not generate the json file sometimes.
It works when there is a `@property` and it does not work when there is not.
Here is the command that failed:
```
vehicle compile --target LossFunction --specification ./src/python/test_json/test_maximum.vcl --outputFile ./src/python/t.json
```

**Comment by MatthewDaggitt** [comment]
Hmm can't seem to reproduce this locally. Can you provide the contents of `test_maximum.vcl` file here?

**Comment by Tgl70** [comment]
The file is now pushed on the branch python-commandline and here is the content:
```
maximum : Bool
maximum = True or False
```

**Comment by MatthewDaggitt** [comment]
Hmm still struggling to reproduce this locally, even on the `python-commandline` branch running the exact same python code... I have pushed a version of your branch up to the repo which has been merged into the latest version of the `dev` branch, so you definitely want to pull the latest of `python-commandline`. Can you check that you still get the same problem now?

One thing I did spot is that in `call_vehicle_to_generate_loss_json` it should be:
```
path_to_json_directory + '/loss_function.json'
``` 
rather than 
```
path_to_json_directory + 'loss_function.json'
```
Not sure why that would make a difference but...

**Comment by MatthewDaggitt** [comment]
@ndslusarz and I managed to diagnose this as the incorrect `isProperty` check in the compilation of loss functions.

**Comment by MatthewDaggitt** [comment]
This was fixed in https://github.com/vehicle-lang/vehicle/pull/254
