### ISSUE TITLE
Let bindings don't type check

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#28]
When running the `andGate` example we end up trying to type the type of the let binding (initially a hole) in infer mode and therefore we error out with:
```
Error: the type of '_' could not be resolved (Line 16, Columns 8-9)
```

**Comment by wenkokke** [comment]
Why is this initially a hole?

**Comment by wenkokke** [comment]
Ah! Let-bindings were originally designed with a mandatory type signature in mind.￼

We can fix the current algorithm by checking whether or not a type signature was provided, and if a type signature was not provided, we infer the type from the let-bound expression, rather than checking the let-bound expression.￼

Alternatively, we can always try to infer the type of the let-bound expression￼, and simply check if the infer type is unifiable with any type provided by the user.￼
