### ISSUE TITLE
Error: Fourier-Motzkin reconstruction failed

### ISSUE THREAD

**Issue by kiczaaa** [vehicle-lang/vehicle#608]
I've run robustness test in my machine, and got this: 
`Error: Fourier-Motzkin reconstruction failed`

The .vcl file cannot be attached here, so I will add the link to my repo: https://github.com/kiczaaa/verification/commit/6b8e5a0dc902118bd1d755e6a343cb4195cc5a31#diff-942afca06d14ee6b0004defca9e7b3c2fabc262fd74bcb6eb3a8ab383a01432a
the file name is: exercise_iris/iris_robustness.vcl

The query was:
`vehicle compileAndVerify --verifier Marabou --specification exercise_iris/iris_robustness.vcl --network iris:exercise_iris/iris_model.onnx --dataset trainingX:exercise_iris/iris_test_data.idx --dataset trainingy:exercise_iris/iris_test_label.idx --parameter epsilon:0.00001`

The vehicle version is 0.3.3.

**Comment by wenkokke** [comment]
Please reinstall Vehicle (`pip install vehicle-lang`) and retry your command.

The latest version is version `0.5.0`.

**Comment by kiczaaa** [comment]
I installed 0.5.0 and still got an error message slightly different from the previous one. 

`Counter-example: found
vehicle: Something went wrong internally. Please report the error shown below to `https://github.com/vehicle-lang/vehicle/issues`.
Error: When reconstructing variable pertubation in counter-example, unable to find variable pertubation_3`

**Comment by MatthewDaggitt** [comment]
Okay so there is a bug in Vehicle here that you've found, but there's also a bug in your specification. In particular Line 82 is `advises input output` but should be `advises perturbedInput output` right? If you fix the spec, then the original Fourier-Motzkin bug no longer appears.

The second bug that you report in v0.5.0 is fixed in https://github.com/vehicle-lang/vehicle/pull/607, and will be fixed in 0.5.1.

**Comment by MatthewDaggitt** [comment]
We can detect this sort of miswritten spec, so https://github.com/vehicle-lang/vehicle/pull/611 has added a warning.
