### ISSUE TITLE
Add function for quantifiers body to loss function sampling interface

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#631]
As discussed. Should get access to the Python function so can use it in FGSM etc.

**Comment by wenkokke** [comment]
This isn't as simple a change as this issue makes it out to be.

In the current implementation, the translation from quantifiers to samplers happens in Vehicle. Therefore, by the time the sampling function reaches Python, we've lost the contextual information that tells us what the quantifier body was.

There are two solutions:

1. Move to a different mode, where Vehicle performs the necessary transformations to prepare for the loss function translation—such as pushing down the negations for DL2 or bunching the conjunctions for STL—but does not compile the logical connectives down to their loss function logic interpretations. The Python side of things then interprets the AST using whatever loss function interpretations are needed. This requires minimal changes: (1) in Vehicle, remove the compilation step that replaces the logical connectives, and (2) in Python, add a function which picks the builtin interpretations based on the loss function target. The machinery to interpret the logical connectives already exists, see: [lossgodel.py](https://github.com/vehicle-lang/vehicle/blob/dev/vehicle-python/src/vehicle_lang/compile/lossgodel.py), [abcboolasfloat.py](https://github.com/vehicle-lang/vehicle/blob/dev/vehicle-python/src/vehicle_lang/compile/abcboolasfloat.py), and [abc.py](https://github.com/vehicle-lang/vehicle/blob/dev/vehicle-python/src/vehicle_lang/compile/abc.py).
 
   _I prefer this option, because it actually *removes* complexity from the Vehicle compiler!_

   - It is easier for users to dynamically define new loss function logics without changing the Vehicle compiler.
      Other researchers will be able to use Vehicle to experiment with their loss function logics!
   - It lets us remove the `Min`, `Max`, `Pow`, and `Sample` builtins.
   - It ensures we'll never again have to add new builtins just to support them in loss functions.

2. Change the `Sample` builtin to be a quantifier, _i.e._, to be of type `(a -> r) -> List r`, and pass the quantifier body explicitly. This complicates the `Sample` operation—turning it into a quantifier—and therefore the only advantage of even compiling `Exists` and `Forall` is standardising the fold over the result (with either a disjunction or a conjunction).

**Comment by wenkokke** [comment]
The other options are to (1) pass the body to `Sample` effectively making it a generic quantifiers, or (2) only revert to emiting the `Exists` and `Forall` quantifiers unchanged.

**Comment by wenkokke** [comment]
#632 adds the predicate to the context when interpreting Forall and Exists on the Python side, fixing this issue for Godel logic.

**Comment by MatthewDaggitt** [comment]
I still stand by my view that we should have no non-trivial logic in the Python side of things. Otherwise, we'll end up having the same problems as Marabou where our functionality is smeared across two different languages.

My proposal is to make the sampling function a bound lambda parameter as well and pass it along with the other resources?

**Comment by wenkokke** [comment]
I think your comparison with Marabou falls flat, because the loss functions aren't useful _outside of_ Python. The chances of us ever adding support for a non-Python loss function backend are minimal. However, the chances of users wanting to experiment with loss functions are, I would say, huge.

**Comment by MatthewDaggitt** [comment]
The plan is to introduce two primitives:
```
maximise "n" : ([<Bool>] -> <Bool>) -> (A -> Bool) -> Bool
minimise "n" : ([<Bool>] -> <Bool>) -> (A -> Bool) -> Bool
```
where first argument is `bigAnd`/`bigOr` and second argument is the body. This should be enough to implement PGD.

**Comment by MatthewDaggitt** [comment]
Fixed by https://github.com/vehicle-lang/vehicle/pull/670
