### ISSUE TITLE
Fix bugs in test suite for check mode on windows

### ISSUE THREAD

**Issue by wenkokke** [vehicle-lang/vehicle#66]
The golden file paths are currently POSIX style, which fails on Windows.

**Comment by MatthewDaggitt** [comment]
Planning on fixing this by checking in the test if we're on Windows and then doing a simple find and replace for `\` to `/` to make the test go through. 

Any objections or better ways of doing it?

**Comment by wenkokke** [comment]
Use [equalFilePath](https://hackage.haskell.org/package/filepath-1.4.2.2/docs/System-FilePath.html#v:equalFilePath)? Perhaps with [canonicalizePath](https://hackage.haskell.org/package/directory-1.3.7.0/docs/System-Directory.html#v:canonicalizePath)?

**Comment by MatthewDaggitt** [comment]
Okay it turns out we have other problems apart from file paths, e.g. Agda module names should obviously depend on their file name and therefore we need the ability to avoid those sort of clashes.

I've therefore added an "ignore list" to the golden file test infrastructure. Basically any pair of lines which both contain the same element in the ignore list will be excluded from the golden file test. While it will allow a few rare false positives through, I think it's the easiest and most flexible approach.
